name: azureml-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]'
      - azureml-defaults
      - numpy
      - scikit-learn
      - tensorflow==2.7
      - opencv-python-headless