name: MLOps Automation

on:
  push:
    branches: [ main ]

jobs:
  start:
    uses: ./.github/workflows/azure-ai.yml
    with:
      data_prep: true
      ai_training: true
      api_creation: true
      data_prep_skip_process: false
      data_prep_skip_split: false
      train_on_local: false
      local_deployment: false
    secrets: inherit